AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with public and private subnets, internet gateway, and NAT gateway.

Parameters:
  VPCCIDR:
    Type: String
    Description: IP range for the VPC 

  PublicSubnetCIDR:
    Type: String
    Description: IP range for the public subnet 

  PrivateSubnetCIDR:
    Type: String
    Description: IP range for the private subnet 

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      Tags: 
                - Key: Name 
                  Value: "My VPC"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    

  InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref MyVPC

